# Generated by Django 5.0 on 2023-12-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phno', models.IntegerField()),
                ('curr_package', models.IntegerField()),
                ('e_id', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phno', models.IntegerField()),
                ('package_name', models.CharField(max_length=100)),
                ('m_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dbms.employee')),
            ],
        ),
    ]
